# AUTHOR:         $maint
# DESCRIPTION:    Minimal Node.js Image using Busybox
FROM jmervine/nodebox:$image
MAINTAINER $maint

ENV NODE_VERSION=$image
ENV NODE_PATH=/src

RUN mkdir -v $NODE_PATH
WORKDIR $NODE_PATH

ONBUILD COPY package.json ${NODE_PATH}/
ONBUILD RUN  npm install
ONBUILD COPY . ${NODE_PATH}

CMD ["npm", "start"]
