# AUTHOR:         $maint
# DESCRIPTION:    Minimal Node.js Image using Busybox
#FROM debian:jessie
FROM debian:wheezy
MAINTAINER $maint

RUN \
  apt-get update && \
  apt-get install -y python make libc6-dev gcc g++ curl git && \
  curl -s http://nodejs.org/dist/v$image/node-v$image-linux-x64.tar.gz | gunzip -c | tar -xf - -C / && \
  apt-get autoremove -y

ENV NODE_VERSION=$image
ENV NODE_PATH=/src
ENV PATH /node-v$image-linux-x64/bin:$PATH

RUN mkdir -v $NODE_PATH
WORKDIR $NODE_PATH

ONBUILD COPY package.json ${NODE_PATH}/
ONBUILD RUN  npm install
ONBUILD COPY . ${NODE_PATH}

CMD ["npm", "start"]
